language: objective-c
osx_image: xcode7.3
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator
script:
- xcodebuild -project 'OCCommunicationLib/ownCloud iOS library.xcodeproj' -scheme 'ownCloud iOS library' -sdk iphonesimulator -UseSanitizedBuildSystemEnvironment=YES
- xctool test -project 'OCCommunicationLib/ownCloud iOS library.xcodeproj' -scheme 'ownCloud iOS library' -sdk iphonesimulator -UseSanitizedBuildSystemEnvironment=YES


before_install:
- brew update
- brew reinstall --HEAD xctool
- sed -i 's/#define k_base_url @\"\"/#define k_base_url @\"$baseUrlTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_webdav_base_url/@\"\"/#define k_webdav_base_url @\"$webdavBaseUrlTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_user @\"\"/#define k_user @\"$userTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_password @\"\"/#define k_password @\"$passwordTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_path_test_folder @\"\"/#define k_path_test_folder @\"$(date +%s)\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_user_to_share @\"\"/#define k_user_to_share @\"$userToShareTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_group_to_share @\"\"/#define k_group_to_share @\"$groupToShareTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- sed -i 's/#define k_remote_user_to_share @\"\"/#define k_remote_user_to_share @\"$remoteUserToShareTravis\"' OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h