language: objective-c
osx_image: xcode6.4
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator
env:
  global:
  - secure: QjbSbwgqLVuybEy75CjkKkLtpdPOXLDERC3dzuFgE3gYUteZavQEyLI/156rlucz9AFLYwIjqcrbo/mO6ecuT93zxblgleuIJsDUhhpv4QhsyYp0Zc5r/w3PBF8D1yyU1n/c1skZrHJljeYPCaqC2EsEjndCYcdEml/mCqXOzhw=
  - secure: N9fjRZiMOlD5ZwN15O/+hcnoMnWkJ5alHFMAVjl8DYeoxDczvxBXgpN55PsQgnoVajgkUjUzQni+QudxeEkPqoMyVTxXaRGSgdFuAFerC9UfNB7+wB7zPbbPXKWNUcaC2iskiXGBAs8M5wGFMTTUOMcw340jaxEzjU+xWJtnAwA=
  - secure: diAOj8Uj3k0A38UEUV7u1XabX6SpXqj9LlFK9NRF9aTPAl7EtuzT/pOG8BilP67km3ADc+AQAqc/qGQqVVx08kiIXiCRfaS0qdQMq6n+Yn7ib7LVEpxdJBe0q55ojZH9EXj/4zNMeY84J187O/B6Hvmli8eZTq1vMTftp0bhZ5U=
  - secure: DkhKi7B4pVSByF5FOiPY/EHUm0cFoFpwg26FJReAuEPmawZ/IYfYbMZSjYUMskfwm+lOLsPB5EgdeTESDU/wUqej1tcfkXPhkXtU/wzsfAVIej/9xj6CHIGRID7wpoYV3pgIBMLPtTJasmSq5zN6o484Xsp6xoUDLhZL4Rd5vnU=

before_install:
- brew update
- brew unlink xctool
- brew install xctool