before_script:
- echo "#define baseUrl @\"https://test1.owncloud.com/owncloud6/\"" > OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- echo "#define webdavBaseUrl @\"https://test1.owncloud.com/owncloud6/remote.php/webdav/\"" >> OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- echo "#define user @\"ios-test\"" >> OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
- echo "#define pathTestFolder @\"test\"" >> OCCommunicationLib/OCCommunicationLibTests/ConfigTests.h
language: objective-c
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator
env:
  global:
    secure: MbEShQ1+0DLmU7MXY58B65YHpm4v6j98Jy8l1yOb8w8k4+f+jpDO+gS1JOHVbxIXzeE5UaGmDrpUiaCo++Dv07S0NGlm5OyD70bBNKGS5IjkTAiYRn3jdsfYgLlUd/titvGQTJB+xrueQbJiYD7pb5SHGI4Bi+HPUFrwJy52wQg=
