language: objective-c
osx_image: xcode7.3
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator

before_install:
- brew reinstall --HEAD xctool
- brew update; brew update
