language: objective-c
osx_image: xcode7.3
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator
script: xcodebuild -project 'OCCommunicationLib/ownCloud iOS library.xcodeproj' -scheme 'ownCloud iOS library' -sdk iphonesimulator -UseSanitizedBuildSystemEnvironment=NO

before_install:
- brew update
- brew reinstall --HEAD xctool