language: objective-c
osx_image: xcode7.3
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator

before_install:
- brew update
- brew reinstall --HEAD xctool
- defaults write com.apple.dt.Xcode UseSanitizedBuildSystemEnvironment -bool YES