language: objective-c
osx_image: xcode7.3
xcode_project: OCCommunicationLib/ownCloud iOS library.xcodeproj
xcode_scheme: ownCloud iOS library
xcode_sdk: iphonesimulator9.3

before_install:
- brew update; brew update
